# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [360, 230]
                    mode: outbound
        wine:
            quality: 100
            filters:
                thumbnail:
                    size: [200, 380]
                    mode: inset
        winemini:
            quality: 75
            filters:
                thumbnail:
                    size: [252, 200]
                    mode: inset
                background:
                    size: [252, 200]
                    color: '#FFFFFF'
        beer:
            quality: 100
            filters:
                thumbnail:
                    size: [200, 380]
                    mode: inset
        food:
            quality: 100
            filters:
                thumbnail:
                    size: [500, 350]
                    mode: inset
